[manager]
splunk-manager ansible_host=10.0.1.32  # Node 6

[indexers]
idx01 ansible_host=10.0.1.205           # Node 3
idx02 ansible_host=10.0.1.143           # Node 4
idx03 ansible_host=10.0.1.46           # Node 5

[searchheads]
sh01 ansible_host=10.0.1.169            # Node 0
sh02 ansible_host=10.0.1.222            # Node 1
sh03 ansible_host=10.0.1.202            # Node 2

[splunk_cluster:children]
manager
indexers
searchheads

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
